<a href="https://colab.research.google.com/github/Sikorsky3301/100-days-of-machine-learning/blob/main/Tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow Fundamentals 101
More Specifically , we're going to cover
  * Introduction to tensorflow
  * Getting information from tensors
  * Manipulating tensors
  * Tensors & Numpy
  * Using @tf.funciton (a way to speed your regular Python functions)
  * Using GPUs with tensorflow (or TPUs)
  * Exercies to try

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.19.0


In [ ]:
# create tensors with tf.constant()

In [ ]:
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check dimensions
scalar.ndim


0

In [ ]:
# creating a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# check the dimension of our vector

In [ ]:
vector.ndim

1

In [ ]:
# creating a matrix

In [ ]:
matrix = tf.constant([[10,70],[12,23]])

In [ ]:
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 70],
       [12, 23]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix = tf.constant([[12.,32.],[12.,32.],[12,32]] , dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[12., 32.],
       [12., 32.],
       [12., 32.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# lets create a tensor

In [ ]:
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                        [10,11,12]],
                      [[12,14,15],
                       [16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[12, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

* scalar : a single number
* vector : a number with direction (e.g : wind speed and direction)
*


* scalar : a single number
* vector : a number with direction (e.g : wind speed and direction)
* matrix : a 2 dim array of numbers
* tensors: an n dimensional array of numbers (when n can be any number , a 0-dimesnional tensor is a scalar , a 1-dimesnional tensor is a vector)


# Creating tensors using tf.variable

In [ ]:
changeable_tensor = tf.Variable([12,7])
unchangeable_tensor = tf.constant([12,7])
changeable_tensor , unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([12,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([12,  7], dtype=int32)>)

In [ ]:
# lets try change the elment from changable tensor

In [ ]:
changeable_tensor[0] = 7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
changeable_tensor[0].assign(7)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
unchangeable_tensor[0].assign[7]

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
tensor_4x4 = tf.constant([[1, 2, 3, 4],
                          [5, 6, 7, 8],
                          [9, 10, 11, 12],
                          [13, 14, 15, 16]])
display(tensor_4x4)

<tf.Tensor: shape=(4, 4), dtype=int32, numpy=
array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int32)>

# <> Creating Random Tensors

In [ ]:
# Creating Random Tensors

# Random tensors are tensors of arbitrary size which contain random numbers.
# They are often used to initialize the weights of neural networks.

# Create a random tensor with a shape of (3, 5)
random_tensor = tf.random.uniform(shape=(3, 5))
display(random_tensor)

In [ ]:
# Create a random tensor using tf.random.Generator.from_seed
# seed means create random but flavour them with seed
random_tensor_seeded = tf.random.Generator.from_seed(42).uniform(shape=(3,2))
random_tensor_seeded2 = tf.random.Generator.from_seed(42).normal(shape=(3,2))

display(random_tensor_seeded)
display(random_tensor_seeded2)
random_tensor_seeded == random_tensor_seeded2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[False, False],
       [False, False],
       [False, False]])>

The difference between `tf.random.uniform` and `tf.random.Generator.from_seed`:

*   `tf.random.uniform` generates a new random tensor each time it is called.
*   `tf.random.Generator.from_seed` creates a generator with a fixed seed. When you generate tensors using this generator, you will get the same "random" sequence of numbers each time, as long as the seed is the same. This is useful for reproducibility in experiments.

Both lines use tf.random.Generator.from_seed(42) to ensure that even though the numbers are random, they will be the same "random" numbers each time you run the code because of the fixed seed (42).

The difference comes from .uniform() and .normal():

.uniform(shape=(3,2)): This generates a tensor of shape (3, 2) where each number is picked randomly from a uniform distribution. This means every number within a certain range has an equal chance of being selected. If you were to plot many numbers from a uniform distribution, you'd get a flat-looking shape.
.normal(shape=(3,2)): This generates a tensor of shape (3, 2) where each number is picked randomly from a normal distribution (also known as a Gaussian distribution or bell curve). In this distribution, numbers closer to the average (mean) are more likely to be selected, and numbers further away are less likely. If you were to plot many numbers from a normal distribution, you'd get a bell shape.
Even though both use the same seed, because they use different methods (.uniform() vs .normal()), they generate completely different sets of random numbers, as you saw in the output where random_tensor_seeded == random_tensor_seeded2 resulted in all False.



# Shiffle the order of elements in tensor

<> Shuffling in tensorflow is important bcs when we have 10k of image data in the form tensor and lets say 8k are of the ramen and 2k are of idli , the ai most likely train on the ramen first so shuffliung shuffle the images so that ai learns both better

In [ ]:
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [2,5]])

not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Shuffle our non-shuffled tensor

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 2,  5],
       [10,  7]], dtype=int32)>

<> make sure to checkout the random seed generation behaviour from docs

https://www.tensorflow.org/api_docs/python/tf/random/set_seed

In [ ]:
tf.random.shuffle(not_shuffled , seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  5],
       [10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled , seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Other Ways to make tensors

Using Numpy

In [ ]:
tf.ones([12,12])


<tf.Tensor: shape=(12, 12), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape = (12,12))

<tf.Tensor: shape=(12, 12), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

> numpy array to tensors

*   **Tensors** are the fundamental data structures in TensorFlow. They are similar to NumPy arrays but have key differences:
    *   Tensors can be used on GPUs or TPUs for faster computation.
    *   Tensors are immutable by default (cannot be changed after creation) unless they are `tf.Variable`.
    *   Tensors can be automatically differentiated (useful for training neural networks).

*   **NumPy arrays** are a fundamental package for scientific computing in Python.
    *   NumPy arrays run on the CPU.
    *   NumPy arrays are mutable (can be changed after creation).
    *   NumPy arrays do not have built-in automatic differentiation capabilities.

In [ ]:
import numpy as np
numpy_A = np.arange(1,25 , dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A = tf.constant(numpy_A , shape = (2,3,4))
B = tf.constant(numpy_A)
A , B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)